name: mobileoffice
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  #dson: 0.13.2
  json: any
  firebase_database: any
  async_loader: "^0.1.1"
  json_annotation: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.7.6
  json_serializable: ^0.3.2

flutter:

  uses-material-design: true
