name: mobileoffice
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  firebase_messaging: "^1.0.3"

  cupertino_icons: ^0.1.0
  flutter_calendar: ^0.0.1
  json: any
  rxdart: any
  #firebase_database: any
  async_loader: "^0.1.1"
  json_annotation: ^0.2.2
  http: "^0.11.3+16"
  shared_preferences: 0.4.2

  calendarro: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.7.6
  json_serializable: ^0.3.2
  event_bus: ^1.0.1
  url_launcher: "^3.0.3"
flutter:

  uses-material-design: true
  assets:
    - img/logo.png
    - img/car_white.png
    - img/parking_full.png
    - img/parking_reserved.jpg
    - img/splash_background.jpg
    - img/holiday.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
